name: flutter_blocx
description: Flutter UI widgets for paginated lists, infinite grids, slivers, reactive forms, and screen state management powered by blocx_core.
version: 1.0.1
repository: https://github.com/abolfazlkhanmohammdi/flutter_blocx
issue_tracker: https://github.com/abolfazlkhanmohammdi/flutter_blocx/issues
topics: [bloc, architecture, lists, forms, flutter]
environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  blocx_core: ^1.1.0
  flutter_bloc: ^9.1.1
  implicitly_animated_list: ^2.3.0
  visibility_detector: ^0.4.0+2
  scroll_to_index: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.5

dependency_overrides:
  blocx_core:
    path: ../blocx_core
